#!/usr/bin/env python3
"""Apply verified annual-horizon discoveries and explicit pet-policy flags."""
from __future__ import annotations
import copy, json
from datetime import date, timedelta
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'assets/data.js'
CHECKED='2026-10-08'
PREFIX='window.SITE_DATA = '

def dates(start,end=None):
    first,last=date.fromisoformat(start),date.fromisoformat(end or start)
    return [(first+timedelta(days=i)).isoformat() for i in range((last-first).days+1)]

def main():
    raw=DATA.read_text(); assert raw.startswith(PREFIX) and raw.rstrip().endswith(';')
    data=json.loads(raw[len(PREFIX):].rstrip()[:-1]); existing={e['id']:e for e in data['events']}
    # Pet-friendly is reserved for an explicit organizer statement, designated
    # pet session, or event whose central activity is bringing/handling pets.
    pet_sources={
      'dog-daze-in-the-maze-wheeler-historic-farm':'https://www.saltlakecounty.gov/wheeler-farm/events--program/',
      'hounds-haunts':'https://www.eventbrite.com/e/hounds-haunts-tickets-1999945899021',
      'howl-o-ween-on-historic-main-street':'https://www.visitparkcity.com/blog/stories/post/tips-for-attending-howl-o-ween/',
      'purple-paw-parade-weber-state':'https://www.alumni.weber.edu/s/953/bp23/interior.aspx?calcid=4875&calpgid=61&cid=6213&crid=0&ecid=6213&gid=1001&pgid=2926&sid=953',
      'swift-pumpkins-dog-daze-in-the-maze':'https://www.swiftpumpkins.com/corn-maze-play-zone-dates-and-times',
      'trunk-or-treat-in-the-arboretum':'https://www.kaysville.gov/calendar.aspx?CID=0&month=10&view=list&year=2026',
      'usu-botanical-center-scarecrow-walk':'https://extension.usu.edu/botanicalcenter/events/scarecrow-walk',
      'snowwiesn-oktoberfest-snowbasin':'https://www.snowbasin.com/events/snowwiesn-oktoberfest/',
      'dogden-festival-2026':'https://ogdendowntown.com/dogden/',
    }
    pet_updated=[]
    for eid,url in pet_sources.items():
        e=existing.get(eid)
        if not e: continue
        flags=e.setdefault('flags',[])
        flags[:]=[flag for flag in flags if flag!='Dog-friendly']
        if 'Pet-friendly' not in flags: flags.append('Pet-friendly')
        # Keep event-specific limits visible in consumer-facing details.
        notes=e.get('Extra notes','')
        if eid=='snowwiesn-oktoberfest-snowbasin' and 'Dogs must be leashed' not in notes:
            e['Extra notes']=(notes+' ' if notes else '')+'Dogs must be leashed and stay on grassy areas; service dogs may enter the lodges.'
        e.setdefault('researchEvidence',{})['petPolicySource']=url
        pet_updated.append(eid)

    def photo_from(eid):
        e=existing.get(eid); return copy.deepcopy(e.get('photo')) if e and e.get('photo') else None
    def photo_by_src(src):
        e=next((item for item in existing.values() if (item.get('photo') or {}).get('src')==src),None)
        return copy.deepcopy(e.get('photo')) if e else None
    def site_photo(src,alt,credit,credit_url,source_url,caption='Previous edition photo'):
        return {'src':src,'alt':alt,'credit':credit,'creditUrl':credit_url,'sourceUrl':source_url,'usageType':'official_web_photo','caption':caption,'reviewedOn':CHECKED}
    def add(*,id,name,region,public_region,types,start,end=None,occurrences=None,holidays,location,times,price,age,description,website,status='Announced 2027',flags=None,is_free=False,communities=None,accessibility=None,photo=None,notable=False,schedule_note='',schedule_confidence='verified-dates',extra='',cost=0,travel='Core / easy day trip',ticket='',is_watch=False):
        occ=[] if is_watch else (occurrences or dates(start,end))
        seasons=[] if is_watch else [s for s in ['Fall','Winter','Spring','Summer'] if s in holidays]
        primary=next((h for h in holidays if h not in ['Fall','Winter','Spring','Summer']),holidays[0])
        e={
          'id':id,'Event / attraction':name,'Region':region,'Category':', '.join(types),'First date':start,
          '2026 schedule':('2027 date and schedule not posted' if is_watch else (', '.join(occ) if len(occ)<=8 else f'{start}–{end or start}')), 'Times':times,
          'Price':price,'Cost':'','Age':age,'Intensity':'','Location':location,'Status':('2027 watch' if is_watch else status),
          'Why / thoughts':description,'Website':website,'Social profile':'','Extra notes':extra,
          'categories':types,'sourceCategories':types,'ghostCount':0,'costCount':cost,'isWatch':is_watch,
          'artKey':'community','socials':[],'photo':copy.deepcopy(photo),'sourceRegion':region,
          'publicRegion':public_region,'publicTypes':types,'sponsored':False,'holidays':holidays,
          'primaryHoliday':primary,'startDate':(None if is_watch else start),'endDate':(None if is_watch else (end or start)),'travelTier':travel,
          'lastVerified':CHECKED,'qaFlags':('WATCH / 2027 SCHEDULE VERIFY' if is_watch else ''),'timezone':'America/Denver','flags':flags or [],'isFree':is_free,
          'rating':None,'occurrenceDates':occ,'scheduleConfidence':('unresolved' if is_watch else schedule_confidence),'scheduleNote':schedule_note,
          'communities':communities or [],'theme':primary.lower().replace(' ','-').replace('’','').replace("'",''),
          'placeholder':f'assets/art/seasonal/winter-community.svg','notable_event':notable,'seasons':seasons,
          'accessibility':accessibility,'ticketUrl':ticket,
          'researchEvidence':{'checkedOn':CHECKED,'sourceUrl':website,'method':'Reviewed organizer, government, venue or official ticket details; past-year program information was not copied into the 2027 listing.'}
        }
        # Select an existing site illustration keyed to the relevant celebration/season.
        theme_map={'Halloween':'halloween','Valentine’s Day':'winter','St. Patrick’s Day':'spring','Memorial Day':'veterans','Easter':'spring','Lunar New Year':'winter','Pride':'pride','Juneteenth':'summer','Independence Day':'summer','Pioneer Day':'summer','Christmas':'christmas','Spring':'spring','Summer':'summer','Winter':'winter'}
        theme=next((theme_map[h] for h in holidays if h in theme_map),'winter')
        e['theme']=theme
        art='community'
        if 'Active & Outdoors' in types: art='active'
        elif 'Live Music & Performance' in types: art='performance'
        elif 'Markets & Shopping' in types: art='market'
        elif 'Nightlife & Parties' in types: art='nightlife'
        seasonal=ROOT/f'assets/art/seasonal/{theme}-{art}.svg'
        e['placeholder']=str(seasonal.relative_to(ROOT)) if seasonal.exists() else f'assets/art/{art}.svg'
        if id in existing:
            source_row=existing[id].get('sourceRow'); existing[id].update(e)
            if source_row is not None: existing[id]['sourceRow']=source_row
        else:
            e['sourceRow']=max((x.get('sourceRow',0) for x in data['events']),default=0)+1
            data['events'].append(e); existing[id]=e
        return e

    added=[]
    def put(**kw): added.append(add(**kw))
    put(id='romeo-juliet-in-concert-eccles-2027',name='Romeo + Juliet in Concert',region='Salt Lake City',public_region='Salt Lake Metro',types=['Live Music & Performance','Community & Culture'],start='2027-02-07',holidays=['Valentine’s Day','Winter'],location='Delta Hall at the Eccles Theater, Salt Lake City',times='Doors 6 PM; show 7 PM',price='Ticketed; seat prices appear in the official ArtTix checkout',age='Recommended 13+; infants not admitted',description='A big-screen showing of Baz Luhrmann’s Romeo + Juliet pairs the film with a live 12-piece ensemble, atmospheric lighting and stage production.',website='https://www.saltlakecountyarts.org/events/romeo-juliet-in-concert/',photo=photo_by_src('assets/photos/reviewed-eccles-theater-12.webp'),accessibility={'summary':'Eccles Theater accessibility information is available through the venue; contact guest services for specific accommodations.'},ticket='https://my.arttix.org/40566/')
    put(id='nhmu-family-seasonal-science-love-bugs-2027',name='NHMU Family Seasonal Science: Love Bugs',region='Salt Lake City',public_region='Salt Lake Metro',types=['Santa & Family','Workshops & Learning'],start='2027-02-13',holidays=['Valentine’s Day','Winter'],location='Natural History Museum of Utah, 301 Wakara Way, Salt Lake City',times='10:15 AM–2:15 PM; drop in during program hours',price='$5 per participant',age='Youth & families; participating children must be accompanied by a paying adult',description='Make handmade Valentine cards and heart-shaped sun catchers, then build a take-home love bug during this hands-on science program.',website='https://nhmu.utah.edu/events/nhmu-family-seasonal-science-love-bugs-0',flags=['Registration recommended','Indoor'],photo=photo_by_src('assets/photos/reviewed-nhmu-45.webp'),accessibility={'summary':'The ticketing page links to NHMU web accessibility information; contact the museum for individual accommodation needs.'},ticket='https://12368a.blackbaudhosting.com/12368a/Family-Seasonal-Science--Love-Bugs--February-13')
    put(id='utah-symphony-princess-bride-concert-2027',name='Utah Symphony: The Princess Bride in Concert',region='Salt Lake City',public_region='Salt Lake Metro',types=['Live Music & Performance','Community & Culture'],start='2027-02-12',end='2027-02-13',occurrences=dates('2027-02-12','2027-02-13'),holidays=['Valentine’s Day','Winter'],location='Maurice Abravanel Hall, 123 W South Temple, Salt Lake City',times='7 PM both nights',price='Ticketed; seat prices appear in the official ArtTix checkout',age='General audience; contact organizer for age guidance',description='Watch The Princess Bride on the big screen while the Utah Symphony performs Mark Knopfler’s score live in sync. The organizer lists lobby wine and movie trivia before the show.',website='https://www.saltlakecountyarts.org/events/the-princess-bride-in-concert/',flags=['Two performances','Indoor'],photo=photo_by_src('assets/photos/reviewed-abravanel-hall-cc-173.webp'),accessibility={'summary':'Utah Symphony and Abravanel Hall publish accessibility information; contact the venue for specific accommodations.'},ticket='https://my.arttix.org/overview/38999/')
    put(id='utah-chinese-new-year-festival-2027',name='Utah Chinese New Year Festival',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Live Music & Performance','Food & Drink'],start='2027-02-06',holidays=['Lunar New Year','Winter'],location='2001 S State Street, Salt Lake City',times='11 AM–4 PM',price='Ticketed; see organizer’s ticket page for current admission',age='All ages',description='A community festival welcoming Lunar New Year with traditional performances, food and cultural activities.',website='https://www.eventbrite.com/e/2027-utah-chinese-new-year-festival-tickets-1993309850421',flags=['Cultural performances','Food','Indoor'],communities=['Chinese / East Asian'],schedule_note='Event listing is dated for 2027; confirm ticket terms and organizer details before travel.')
    put(id='price-city-st-patricks-day-parade-2027',name='Price City St. Patrick’s Day Parade',region='Eastern Utah',public_region='Eastern Utah',types=['Community & Culture','Live Music & Performance'],start='2027-03-14',holidays=['St. Patrick’s Day','Spring'],location='Price City, Carbon County',times='Parade time and route to be announced',price='Free to watch; program details forthcoming',age='All ages',description='Price City’s 2027 calendar lists its annual St. Patrick’s Day Parade for March 14. The route and event-day schedule will help shape a small-town parade outing.',website='https://www.priceutah.gov/events.html',flags=['Outdoor parade'],communities=['Irish / Irish American'],schedule_note='The city has announced the date; parade time and route are not yet listed.')
    put(id='utah-summer-games-2027',name='Larry H. Miller Utah Summer Games 2027',region='Cedar / Iron County',public_region='Cedar / Iron County',types=['Active & Outdoors','Community & Culture'],start='2027-03-19',end='2027-06-26',occurrences=['2027-03-19','2027-03-20','2027-04-15','2027-04-16','2027-04-17','2027-05-20','2027-05-21','2027-05-22','2027-06-03','2027-06-04','2027-06-05','2027-06-10','2027-06-11','2027-06-12','2027-06-14','2027-06-15','2027-06-18','2027-06-19','2027-06-25','2027-06-26'],holidays=['Spring','Summer'],location='Southern Utah University and partner venues in Iron County',times='Competition schedule varies by sport; opening ceremony June 4',price='Varies by sport and registration; spectators should check the event schedule',age='Youth, adult and adaptive sports; varies by event',description='Utah’s statewide amateur sports program spreads competitions across spring and summer. The announced tentative calendar includes youth soccer, basketball, water polo, baseball and a June 4 opening ceremony.',website='https://utahsummergames.org/news/2026/9/1/general-larry-h-miller-utah-summer-games-releases-2027-tentative-calendar.aspx',flags=['Multi-day','Multiple venues','Tentative calendar'],photo=site_photo('assets/photos/utah-summer-games-opening-2026-reviewed.webp','The Utah Summer Games mascot leads the 2026 opening celebration at Eccles Coliseum.','Southern Utah University','https://www.suu.edu/news/2026/06/suu-utah-summer-games-opening-ceremony.html','https://www.suu.edu/news/images/2026/06-utah-summer-games-thor.webp'),communities=['Sports community'],schedule_note='Organizer calls the published calendar tentative; recheck each sport before traveling.',schedule_confidence='announced-tentative',notable=True,travel='Utah outing')
    put(id='west-jordan-egg-hunt-2027',name='West Jordan Annual Egg Hunt',region='West Jordan',public_region='Salt Lake Metro',types=['Santa & Family','Community & Culture'],start='2027-03-27',holidays=['Easter','Spring'],location='West Jordan Soccer Complex, 8070 S 4000 W, West Jordan',times='9 AM sharp; arrive early to park and reach the assigned field',price='Free',age='Children ages 2–15; ADA-accessible area',description='A quick, colorful egg hunt with age-group fields and an accessible pavilion area. The 9 AM start is sharp and the eggs are gathered within minutes.',website='https://www.westjordan.utah.gov/city-events/egg-hunt/',flags=['Free admission','Family activities','ADA-accessible area','Outdoor'],is_free=True,accessibility={'summary':'An ADA field uses a flat concrete surface in the pavilion.'},photo=None)
    put(id='salt-lake-temple-celebration-2027',name='Salt Lake Temple Celebration & Public Open House',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Workshops & Learning'],start='2027-04-05',end='2027-10-01',occurrences=dates('2027-04-05','2027-10-01'),holidays=['Spring','Summer','Fall'],location='Temple Square, 50 N West Temple, Salt Lake City',times='Timed tour tickets; daily hours vary, closed Sundays',price='Free; timed tickets required',age='All welcome',description='For a limited time, visitors can tour the restored Salt Lake Temple and explore Temple Square experiences. Public tours run April 5 through October 1, 2027; reserve a timed ticket.',website='https://www.churchofjesuschrist.org/events/salt-lake-temple-celebration-event?lang=eng',flags=['Free admission','Timed tickets','Indoor/outdoor'],photo=site_photo('assets/photos/salt-lake-temple-spring-2026-official.webp','The Salt Lake Temple rises above spring flowers at Temple Square.','Intellectual Reserve, Inc.','https://newsroom.churchofjesuschrist.org/article/salt-lake-temple-celebration-volunteers','https://newsroom.churchofjesuschrist.org/media/960x540/o7txcs28zf9nejswr9dv02jk5n1g0grm4zlaoofw.jpeg','Venue photo'),is_free=True,accessibility={'summary':'The Temple Square celebration highlights accessibility enhancements; check the official visitor page for mobility and other access details.'},schedule_note='Tour hours and ticket releases vary; check current official availability before visiting.',notable=True,travel='Core / easy day trip')
    put(id='living-traditions-festival-2027',name='Living Traditions Festival',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Live Music & Performance','Food & Drink','Markets & Shopping','Workshops & Learning'],start='2027-05-21',end='2027-05-23',holidays=['Spring'],location='Washington Square and Library Square, downtown Salt Lake City',times='Three-day festival; daily hours and program to be announced',price='Expected free admission; 2027 admission details not posted',age='All ages',description='Traditional music, dance, crafts, food and local partnerships bring Utah’s many cultural communities to downtown Salt Lake for a three-day festival.',website='https://saltlakearts.org/programs/living-traditions-festival',flags=['Cultural performances','Food','Kids activities','Accessibility information'],communities=['Multicultural / Community'],accessibility={'summary':'The organizer provides festival access information, including ADA seating, accessible restrooms, drop-off and route notes. Check the 2027 page for updated details.'},photo=site_photo('assets/photos/living-traditions-festival-dance-2025.webp','Dancers perform at the 2025 Living Traditions Festival in Salt Lake City.','Salt Lake City Arts Council','https://saltlakearts.org/news/living-traditions-this-weekend','https://saltlakearts.org/images/econa-article-images/326/full/1400/ltf-2025-press-1.jpeg'),schedule_note='2027 dates are announced; hours, lineup, admission and updated access notes are forthcoming.',notable=True)
    put(id='west-jordan-memorial-day-ceremony-car-show-2027',name='West Jordan Memorial Day Ceremony & Car Show',region='West Jordan',public_region='Salt Lake Metro',types=['Community & Culture','Active & Outdoors'],start='2027-05-31',holidays=['Memorial Day','Spring'],location='Veterans Memorial Park, West Jordan',times='Car show 10 AM–2 PM; ceremony 11:30 AM–noon',price='Free; food trucks are extra',age='All ages',description='A public remembrance ceremony shares Veterans Memorial Park with a classic car show and food trucks. Leashed dogs are allowed.',website='https://www.westjordan.utah.gov/city-events/memorial-day-ceremony-and-car-show/',flags=['Free admission','Outdoor ceremony','Car show','Food available','Pet-friendly'],is_free=True,photo=None,accessibility={'summary':'Contact West Jordan City for park access questions and accommodations.'},extra='Dogs are permitted on leash. 2027 car registration and food truck details will be posted closer to the event.',notable=True)
    put(id='run-of-remembrance-memorial-day-2027',name='Run of Remembrance — Memorial Day',region='Utah County',public_region='Utah County',types=['Active & Outdoors','Community & Culture'],start='2027-05-31',holidays=['Memorial Day','Spring'],location='Robinson Park, 100 E Main Street, American Fork',times='10K and 5K 8 AM; Memorial Mile 9 AM; Kids 1K 9:15 AM',price='Registration: 10K $49.95; 5K $39.95; Memorial Mile $27.95; Kids 1K $16.95, plus fees',age='All ages; Kids 1K ages 1–12',description='A Memorial Day race with a 10K, 5K, one-mile option and children’s 1K, starting and finishing at Robinson Park.',website='https://runtasticevents.com/races/run-of-remembrance/',flags=['Registration required','Multiple distances','Kids run'],photo=None,ticket='https://runsignup.com/Race/Register/?raceId=48183',notable=True)
    put(id='soldier-hollow-classic-sheepdog-2027',name='Soldier Hollow Classic Sheepdog Championship & Festival',region='Park City & Wasatch Back',public_region='Park City & Wasatch Back',types=['Community & Culture','Active & Outdoors','Live Music & Performance','Food & Drink'],start='2027-05-28',end='2027-05-31',holidays=['Memorial Day','Spring'],location='Soldier Hollow Nordic Center, 2002 Soldier Hollow Lane, Midway',times='Four-day festival; daily run orders and activities vary',price='2027 tickets on sale March 2027; children age 5 and under free; adult/youth/family prices TBD',age='All ages',description='Watch world-class border collies move sheep through a challenging course, then spend time at the festival with food, vendors and family activities.',website='https://soldierhollowclassic.com/2026-tickets/',flags=['Outdoor','Multi-day','Children 5 and under free'],photo=site_photo('assets/photos/soldier-hollow-classic-2025.webp','A sheepdog handler and flock compete at Soldier Hollow Classic in 2025.','Heber Valley Tourism','https://www.gohebervalley.com/newsroom-soldier-hollow-classic-sheepdog-championship-2025/','https://assets.earthdiver.com/media/media-image-3179742.jpg?h=2832&tick=1746462688423&w=4256'),accessibility={'summary':'Contact the organizer about accessible routes and seating at Soldier Hollow Nordic Center.'},schedule_note='The dates are posted; the organizer says 2027 tickets go on sale in March and current ticket prices are TBD.',notable=True)
    put(id='dinosaur-roundup-rodeo-vernal-2027',name='Vernal’s Dinosaur Roundup Rodeo',region='Eastern Utah',public_region='Eastern Utah',types=['Community & Culture','Live Music & Performance'],start='2027-06-17',end='2027-06-19',holidays=['Father’s Day','Summer'],location='Western Park Arena, Vernal',times='Three rodeo nights; start times on the ticket page',price='Assigned-seat tickets; see official PurplePass seller for current prices',age='All ages; children 2 and under may sit on an adult’s lap',description='Three nights of rodeo competition and arena entertainment in Vernal over Father’s Day weekend.',website='https://vernalrodeo.com/tickets/',flags=['Tickets required','Assigned seating','Outdoor arena'],photo=site_photo('assets/photos/dinosaur-roundup-rodeo-2026-winner.webp','Cole Reiner competes at the 2026 Dinosaur Roundup Rodeo in Vernal.','Vernal’s Dinosaur Roundup Rodeo','https://vernalrodeo.com/2026results/','https://vernalrodeo.com/wp-content/uploads/2026/06/Cole-portrait.png'),communities=['Rodeo / Western'],schedule_note='The organizer has announced June 17–19, 2027. The site identifies PurplePass as the only authorized ticket seller.',ticket='https://vernalrodeo.com/tickets/',travel='Overnight / destination')
    put(id='utah-festival-opera-2027-season',name='Utah Festival Opera & Musical Theatre — 2027 Season',region='Cache Valley',public_region='Cache / Box Elder',types=['Live Music & Performance','Community & Culture'],start='2027-06-18',end='2027-07-13',occurrences=dates('2027-06-18','2027-07-13'),holidays=['Summer'],location='Utah Theatre and partner venues, Logan',times='Showtimes vary by production',price='Tickets on sale through the company; prices vary by show and seat',age='General audience; check each production',description='A summer repertory season in Logan pairs opera and musical theatre, with five announced productions: Pagliacci, Fiddler on the Roof, The Wizard of Oz, Tenderly and Lend Me a Tenor.',website='https://utahfestival.org/',flags=['Multiple productions','Indoor'],photo=site_photo('assets/photos/utah-festival-opera-my-fair-lady.webp','Performers in a Utah Festival Opera production of My Fair Lady.','Waldron Creative / Visit Utah','https://www.visitutah.com/things-to-do/events/utah-festival-opera','https://www.visitutah.com/azure/cmsroot/visitutah/media/site-assets/three-season-photography/northern-utah/logan/logan_utah-festival_waldron-creative_my-fair-lady_1.jpg'),notable=True,travel='Utah outing')
    put(id='utah-ukulele-festival-2027',name='Utah Ukulele Festival',region='Cache Valley',public_region='Cache / Box Elder',types=['Live Music & Performance','Community & Culture','Workshops & Learning'],start='2027-08-07',holidays=['Summer'],location='Willow Park, Logan',times='10 AM–8 PM',price='Free',age='All ages',description='A full day of ukulele performances and community music at Willow Park, with programming celebrating the instrument and Pacific Island cultures.',website='https://utahukefest.com/',flags=['Free admission','Outdoor','Live music','Workshops'],is_free=True,communities=['Pacific Islander'],schedule_confidence='verified-dates',photo=None,travel='Utah outing')
    put(id='das-energi-festival-2027',name='DAS ENERGI Festival',region='Salt Lake / Magna',public_region='Salt Lake Metro',types=['Nightlife & Parties','Live Music & Performance'],start='2027-08-06',end='2027-08-08',holidays=['Summer'],location='The Saltair, 12408 W Saltair Drive, Magna',times='Friday and Saturday 5 PM–2 AM; Sunday 4 PM–1 AM',price='Ticketed; check official ticket seller for current tiers and fees',age='18+; government-issued photo ID required',description='A three-night electronic music festival at the Saltair, with late sets, a 21+ bar area and rideshare pickup. No re-entry.',website='https://dasenergifestival.com/info-faq/',flags=['18+','Nightlife','Outdoor','No re-entry','Paid parking'],extra='Parking is $20 per car per day. The festival runs rain or shine. ADA accommodation form is linked by the organizer.',accessibility={'summary':'The organizer links an ADA accommodation form through The Saltair.'},schedule_confidence='verified-dates',notable=True)
    put(id='utah-summer-dance-festival-2027',name='Utah Summer Dance Festival',region='Salt Lake Valley',public_region='Salt Lake Metro',types=['Live Music & Performance','Community & Culture'],start='2027-08-21',holidays=['Summer'],location='South Salt Lake Community Center, South Salt Lake',times='Festival hours to be announced',price='Admission details forthcoming',age='All ages',description='A summer dance showcase bringing performances and community groups together for a day of movement and live entertainment.',website='https://utahsummerdancefestival.org/registration/vendor/',schedule_note='The organizer has posted August 21, 2027 for the festival; hours and admission details are still forthcoming.')
    put(id='farmington-festival-days-2027',name='Farmington Festival Days',region='Davis County',public_region='Davis County',types=['Community & Culture','Active & Outdoors','Live Music & Performance'],start='2027-07-12',end='2027-07-17',holidays=['Summer'],location='Farmington City parks and venues',times='Individual event hours vary',price='Some activities may be free; program-specific admission details forthcoming',age='All ages',description='Farmington’s summer celebration returns July 12–17, 2027, with tournaments and community activities. The full schedule will identify locations and ticket requirements.',website='https://www.farmington.utah.gov/wp-content/uploads/2026/08/August-Newsletter.pdf',flags=['Community festival','Multi-day'],schedule_note='The city newsletter lists these dates as a save-the-date; the full program is forthcoming.')
    put(id='aloha-fest-utah-2027',name='Aloha Fest Utah',region='Utah County',public_region='Utah County',types=['Community & Culture','Live Music & Performance','Food & Drink'],start='2027-07-24',holidays=['Summer'],location='City Center Park, Orem',times='Festival hours to be announced',price='Admission details forthcoming',age='Family-friendly; all ages',description='A Pacific Island cultural festival with music, dance, food, traditions and activities for families, organized by Aloha In Utah Foundation.',website='https://alohafestutah.com/',photo=site_photo('assets/photos/aloha-fest-utah-2026.webp','Families gather at the 2026 Aloha Fest Utah in Orem.','Aloha In Utah Foundation','https://alohafestutah.com/','https://img1.wsimg.com/isteam/ip/de0507c8-74f5-46da-9ccd-b211a221d2fd/IMG_8794.jpeg'),flags=['Family-friendly','Cultural performances','Food'],communities=['Pacific Islander'],schedule_note='The organizer has announced July 24, 2027; festival hours and admission information are forthcoming.',notable=True)
    put(id='carbon-county-fair-2027',name='Carbon County Fair',region='Eastern Utah',public_region='Eastern Utah',types=['Community & Culture','Farms & Harvest','Active & Outdoors'],start='2027-06-03',end='2027-06-05',holidays=['Summer'],location='Carbon County Fairgrounds, Price',times='Daily hours and program to be announced',price='Admission varies by fair event',age='All ages',description='A three-day county fair in Price with agricultural exhibits, local competitions, food and community entertainment.',website='https://www.carbonutahfair.com/',flags=['Outdoor','Multi-day'],travel='Utah outing')
    put(id='utah-valley-marathon-2027',name='Utah Valley Marathon & Half Marathon',region='Utah County',public_region='Utah County',types=['Active & Outdoors','Community & Culture'],start='2027-06-04',end='2027-06-05',holidays=['Summer'],location='Provo Canyon; expo and finish festival at Utah Valley Convention Center and Provo Historic Courthouse Grounds',times='Marathon starts June 5 at 6 AM; packet pickup June 4, 10 AM–8 PM',price='Marathon registration $134 through Nov. 4, then rises; other distances have separate fees',age='Runners and spectators; age rules vary by distance',description='A two-day race weekend with marathon, half marathon and shorter distances, course support and a finish-line festival.',website='https://www.utahvalleymarathon.com/',photo=site_photo('assets/photos/utah-valley-marathon-course.webp','A Utah Valley Marathon runner races along the Provo Canyon course.','Utah Valley Marathon','https://www.utahvalleymarathon.com/utah-valley-marathon-info','https://www.utahvalleymarathon.com/wp-content/uploads/2015/03/canyon.jpg'),accessibility={'summary':'The organizer lists mobility-impaired race divisions, including athletes with physical disabilities, athletes who are blind and duo participants; check each distance’s current rules.'},ticket='https://www.utahvalleymarathon.com/utah-valley-marathon-info',flags=['Registration required','Multiple distances','Multi-day'])
    put(id='utah-own-spring-market-2027',name='Utah’s Own Spring Market',region='Utah County',public_region='Utah County',types=['Markets & Shopping','Food & Drink','Community & Culture'],start='2027-05-09',holidays=['Mother’s Day','Spring'],location='Oliver’s Place, 125 S 2000 W, Pleasant Grove',times='9 AM–2 PM (market listing)',price='Free to browse; purchases extra',age='All ages',description='Utah food and maker vendors offer bread, meats, treats, spices and body care products in a market timed for Mother’s Day gifts.',website='https://www.usefestkit.com/events/utah-department-of-agriculture-and-food/utah-s-own-spring-market',flags=['Free admission','Food and vendors','Indoor/Outdoor'],is_free=True,schedule_note='The market’s 2027 listing shows May 9; confirm organizer hours as the date approaches.')
    put(id='utah-pride-festival-2027-watch',name='Utah Pride Festival — 2027 planning watch',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Live Music & Performance'],start='',holidays=['Pride','Summer'],location='Salt Lake City; 2027 venue to be announced',times='2027 schedule not posted',price='2027 admission details not posted',age='Check organizer guidance',description='Utah Pride Festival brings LGBTQ+ community groups, performances and celebration to downtown Salt Lake City. The organizer has not posted the 2027 date or venue.',website='https://www.utahpridecenter.org/calendar/utah-pride-festival',is_watch=True)
    put(id='hibernian-society-st-patricks-parade-2027-watch',name='Salt Lake St. Patrick’s Day Parade & Siamsa — 2027 planning watch',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Live Music & Performance','Food & Drink'],start='',holidays=['St. Patrick’s Day','Spring'],location='Downtown Salt Lake City; route and site to be confirmed',times='2027 schedule not posted',price='2027 admission details not posted',age='All ages; festival policies to be confirmed',description='The Hibernian Society of Utah’s annual parade and Siamsa brings Irish music, dance and community celebration downtown. Its 2027 date and program are not posted yet.',website='https://www.irishinutah.com/parade',is_watch=True,communities=['Irish / Irish American'])
    put(id='thanksgiving-point-valentine-dinner-dance-2027-watch',name='Valentine Dinner Dance at Thanksgiving Point — 2027 planning watch',region='Utah County',public_region='Utah County',types=['Food & Drink','Live Music & Performance'],start='',holidays=['Valentine’s Day','Winter'],location='Thanksgiving Point, Lehi; venue to be confirmed',times='2027 dinner and dance schedule not posted',price='2027 ticket price not posted',age='Adults / general audience',description='Thanksgiving Point’s annual Valentine dinner dance pairs a seated dinner with live music from The Salamanders and dancing. The organizer has not posted its 2027 date or ticket details.',website='https://thanksgivingpoint.org/events/valentine-dinner-dance/',is_watch=True)
    put(id='thanksgiving-point-tulip-festival-2027-watch',name='Thanksgiving Point Tulip Festival — 2027 dates pending',region='Utah County',public_region='Utah County',types=['Farms & Harvest','Active & Outdoors','Community & Culture'],start='',holidays=['Spring'],location='Ashton Gardens at Thanksgiving Point, Lehi',times='2027 dates not posted',price='2027 admission price not posted',age='All ages',description='Ashton Gardens turns into a seasonal walk through tulips and spring displays. Thanksgiving Point says the festival will return in 2027; the new dates are not posted.',website='https://thanksgivingpoint.org/events/tulip-festival/',is_watch=True,photo=photo_from('thanksgiving-point-scarecrow-festival'))
    put(id='draper-memorial-day-ceremony-2027-watch',name='Draper Memorial Day Ceremony — 2027 planning watch',region='Salt Lake Valley',public_region='Salt Lake Metro',types=['Community & Culture'],start='',holidays=['Memorial Day','Spring'],location='Gold Star Families Memorial Monument at Draper Park, Draper',times='2027 ceremony time not posted',price='Free',age='All ages',description='Draper’s public ceremony honors those who died in military service at the Gold Star Families Memorial Monument. The city has not posted its 2027 program.',website='https://www.draperutah.gov/Calendar.aspx?EID=5821',flags=['Free admission'],is_watch=True,is_free=True)

    put(id='fanx-salt-lake-2027',name='FanX Salt Lake Comic Convention 2027',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Live Music & Performance'],start='2027-03-11',end='2027-03-13',holidays=['Spring'],location='Salt Palace Convention Center, Salt Lake City',times='Three-day convention; guest schedules and daily hours to be announced',price='3-Day MultiPass $79; Ruby $132; VIP $359, plus taxes and fees',age='All ages; check ticket and guest policies',description='A three-day pop-culture convention with celebrity guests, cosplay, fan panels, artists and exhibitor halls at the Salt Palace.',website='https://fanxsaltlake.com/',flags=['Multi-day','Convention','Tickets required'],photo=photo_from('fanx-salt-lake-2026'),ticket='https://fanxsaltlake.com/tickets/',schedule_note='2027 dates and ticket tiers are posted; guest schedule and daily hours are forthcoming.',notable=True)
    put(id='utah-state-fair-2027',name='Utah State Fair 2027',region='Salt Lake City',public_region='Salt Lake Metro',types=['Community & Culture','Farms & Harvest','Food & Drink','Active & Outdoors'],start='2027-09-09',end='2027-09-19',holidays=['Fall'],location='Utah State Fairpark, 155 N 1000 W, Salt Lake City',times='Fair dates announced; daily hours and program to be announced',price='2027 admission and ride prices not posted',age='All ages',description='Utah’s state fair fills the Fairpark with livestock and agricultural exhibits, competitions, fair food, carnival rides, concerts and arena shows.',website='https://www.utahstatefair.com/',photo=site_photo('assets/photos/utah-state-fair-carnival-visit-utah.webp','A Ferris wheel and carnival midway at the Utah State Fair.','Linda Iverson / Visit Utah','https://www.visitutah.com/articles/utah-state-fair','https://www.visitutah.com/azure/cmsroot/visitutah/media/site-assets/three-season-photography/wasatch-metro/salt-lake-city-5/utah-state-fair_carnival_iverson-linda_457.jpg'),flags=['Outdoor','Multi-day','Rides and attractions','Food vendors'],schedule_note='The official 2027 calendar lists September 9–19; daily hours, performances and prices will be published closer to the fair.',notable=True)
    put(id='holi-festival-of-colors-2027-watch',name='Holi Festival of Colors at Radha Krishna Temple — 2027 planning watch',region='Utah County',public_region='Utah County',types=['Community & Culture','Live Music & Performance'],start='',holidays=['Holi','Spring'],location='Radha Krishna Temple, Spanish Fork',times='2027 date and hours not posted',price='2027 admission details not posted',age='All ages; event policies to be confirmed',description='The annual Festival of Colors celebrates Holi with music, dance and colored powder at the Radha Krishna Temple. The organizer has not posted its 2027 date or admission details.',website='https://www.festivalofcolorsusa.com/',is_watch=True,communities=['Hindu','South Asian'],schedule_note='Watch for the organizer’s 2027 announcement; do not treat a calculated lunar date as a confirmed event date.')

    # Price fields/annual taxonomy are already present; preserve exact existing structure.
    data['meta']['updated']='October 8, 2026'
    data['meta']['eventCount']=len(data['events'])
    # Keep an explicit, source-linked pet-policy flag alongside the visible
    # practical-detail label. This lets the guide and social toolkit distinguish
    # verified dog access from service-animal access or animal attractions.
    for event in data['events']:
      if 'Pet-friendly' not in (event.get('flags') or []): continue
      evidence=event.get('researchEvidence') or {}
      policy_source=event.get('petPolicySource') or evidence.get('petPolicySource') or event.get('Website')
      if not policy_source: raise ValueError(f"Pet-friendly listing has no policy source: {event['id']}")
      event['petFriendlyVerified']=True
      event['allowedPets']=['dogs']
      event['petPolicySource']=policy_source

    data['meta']['confirmedCount']=sum(not e.get('isWatch') for e in data['events'])
    data['meta']['watchCount']=sum(bool(e.get('isWatch')) for e in data['events'])
    data['meta']['realImageCount']=sum(bool(e.get('photo')) for e in data['events'])
    data['meta']['localPhotoListings']=data['meta']['realImageCount']
    data['meta']['accessibilityListings']=sum(bool(e.get('accessibility')) for e in data['events'])
    data['planningHorizon']={'from':'2026-10-08','through':'2027-10-31','note':'Holiday dates are distinct from organizer-announced event dates. Religious observance dates can vary by tradition, sunset and local moon sighting. Watchlist records are not add-to-calendar dates.'}
    DATA.write_text(PREFIX+json.dumps(data,ensure_ascii=False,indent=2)+';\n')
    ledger={
      'checkedOn':CHECKED,'scope':['annual Utah event research','Valentine’s Day','St. Patrick’s Day','Memorial Day','Easter','Lunar New Year','Pride','spring and summer cultural festivals','major 2027 annual events','FanX Salt Lake Comic Convention','Utah State Fair','Holi Festival of Colors','pet access audit'],
      'planningHorizon':data['planningHorizon'],'addedOrUpdatedIds':[e['id'] for e in added],
      'petFlagsUpdated':pet_updated,
      'result':{'addedOrUpdated':len(added),'confirmedAddedOrUpdated':sum(not e.get('isWatch') for e in added),'watchAddedOrUpdated':sum(bool(e.get('isWatch')) for e in added),'petListingsFlagged':len(pet_updated),'totalEvents':len(data['events']),'photoListings':data['meta']['realImageCount']},
      'sources':[
        'https://nhmu.utah.edu/events/nhmu-family-seasonal-science-love-bugs-0','https://www.saltlakecountyarts.org/events/romeo-juliet-in-concert/','https://www.saltlakecountyarts.org/events/the-princess-bride-in-concert/','https://www.priceutah.gov/events.html','https://utahsummergames.org/news/2026/9/1/general-larry-h-miller-utah-summer-games-releases-2027-tentative-calendar.aspx','https://www.westjordan.utah.gov/city-events/egg-hunt/','https://www.churchofjesuschrist.org/events/salt-lake-temple-celebration-event?lang=eng','https://saltlakearts.org/programs/living-traditions-festival','https://www.westjordan.utah.gov/city-events/memorial-day-ceremony-and-car-show/','https://runtasticevents.com/races/run-of-remembrance/','https://soldierhollowclassic.com/','https://vernalrodeo.com/tickets/','https://utahfestival.org/','https://utahukefest.com/','https://dasenergifestival.com/info-faq/','https://utahsummerdancefestival.org/registration/vendor/','https://www.farmington.utah.gov/wp-content/uploads/2026/08/August-Newsletter.pdf','https://alohafestutah.com/','https://www.carbonutahfair.com/','https://www.utahvalleymarathon.com/','https://fanxsaltlake.com/','https://www.utahstatefair.com/','https://www.festivalofcolorsusa.com/','https://www.usefestkit.com/events/utah-department-of-agriculture-and-food/utah-s-own-spring-market','https://www.irishinutah.com/parade','https://thanksgivingpoint.org/events/valentine-dinner-dance/','https://thanksgivingpoint.org/events/tulip-festival/'
      ],
      'watchlistNotes':'Only event dates directly announced by organizers are calendar dates. A 2027 date plus a past-year description remains a current organizer announcement; no past-year venue, price or lineup is treated as current unless the organizer says it carries forward.',
      'petPolicy':'Pet-friendly is applied only to explicit pet admission, a named dog session, or an event whose central activity is attending with a pet. Service-animal access alone is not sufficient. Event-specific leash and area limits remain in notes.'
    }
    out=ROOT/'research'/'annual-horizon-pass-2026-10-08.json';out.write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps(ledger['result'],indent=2));print('pet IDs',len(pet_updated));print('annual IDs',len(added))

if __name__=='__main__': main()
