"""Source-backed archive additions; preserve historical dates rather than invent publication dates."""
import json,pathlib,datetime,re
p=pathlib.Path('assets/data.js');s=p.read_text();d=json.loads(s[s.index('{'):].strip().rstrip(';'));new=[]
def add(name,start,end,region,types,location,hours,price,description,url,holidays=None,notes='',flags=None,communities=None,notable=False,recurrence='annual',accessibility=None,bydate=None):
 id=re.sub('[^a-z0-9]+','-',name.lower()).strip('-')+'-2026'
 if any(e['id']==id for e in d['events']):return
 dates=[];a=datetime.date.fromisoformat(start);b=datetime.date.fromisoformat(end)
 while a<=b:dates.append(a.isoformat());a+=datetime.timedelta(days=1)
 free=price.lower().startswith('free');fs=list(flags or []);fs+=['Free admission'] if free else []
 e={'id':id,'Event / attraction':name,'Region':region,'Category':' / '.join(types),'First date':start,'2026 schedule':', '.join(dates),'Times':hours,'Price':price,'Cost':'','Age':'All ages / general audience','Intensity':'','Location':location,'Status':'Confirmed 2026; past' if end<'2026-10-06' else 'Confirmed 2026','Why / thoughts':description,'Website':url,'Social profile':'','Extra notes':notes,'categories':types,'sourceCategories':types,'sourceRegion':region,'publicRegion':region,'publicTypes':types,'ghostCount':0,'costCount':1 if free else 3,'isWatch':False,'artKey':'community','socials':[],'photo':None,'sponsored':False,'holidays':list(dict.fromkeys(['Fall',*(holidays or [])])),'primaryHoliday':(holidays or ['Fall'])[0],'startDate':start,'endDate':end,'travelTier':'Utah outing','lastVerified':'2026-10-06','qaFlags':'','timezone':'America/Denver','flags':fs,'isFree':free,'rating':None,'occurrenceDates':dates,'scheduleConfidence':'verified-dates','scheduleNote':'','communities':communities or [],'theme':'thanksgiving','placeholder':'assets/art/community.svg','notable_event':notable,'recurrence':recurrence,'accessibility':accessibility,'researchEvidence':{'checkedOn':'2026-10-06','sourceUrl':url,'method':'Read dated primary organizer, venue or government archive; followed program and ticket links where reachable. Historical edition, not a future-date estimate.'}}
 if bydate:e['hoursByDate']=bydate
 new.append(e);d['events'].append(e)
C=['Community & Culture'];M=['Community & Culture','Markets & Shopping','Live Music & Performance','Food & Drink'];A=['Active & Outdoors'];S='Salt Lake Metro';U='Utah County';P='Park City & Wasatch Back';D='Davis County';L='Cache / Box Elder';E='Eastern Utah';T='Tooele';I='Cedar / Iron County';SU='Southern Utah';SO='Statewide / Other'
# Labor Day coverage: separate cultural traditions and distinct paid experiences.
add('Midway Swiss Days','2026-09-04','2026-09-05',P,M,'Midway Town Square, 75 W 100 N, Midway','8 AM–8 PM','Free admission; shuttle parking $15; purchases extra','A Swiss heritage celebration with artisan booths, Swiss German food, live entertainment and a Saturday parade. Busy walkways make this a substantial festival outing.','https://www.midwayswissdays.org/2026-event',['Labor Day'],notes='Saturday parade at 10 AM. Pets are not permitted; service animals excepted.',flags=['Outdoor'],notable=True)
add('Golden Onion Days','2026-09-03','2026-09-07',U,M,'Payson city parks and downtown, Payson','Program varies by activity; opening concert Sep 3 at 6 PM','Free opening concert; carnival, race entries and purchases extra','Payson’s harvest and homecoming celebration combines concerts, a carnival, a parade, fireworks, art and flower shows, and a Labor Day car show.','https://www.paysonutah.gov/386/Golden-Onion-Days',['Labor Day'],flags=['Outdoor'],notable=True)
add('Festival Latinoamericano','2026-09-04','2026-09-07',U,M,'Utah County Historic Courthouse, 51 S University Ave, Provo','Fri 5:45–10 PM; Sat 10 AM–10 PM; Sun 6–8 PM; Mon 10 AM–10 PM','Free admission; food and purchases extra','Music, dance, food and crafts celebrate Latin American cultures in downtown Provo. Sunday is a stage-only evening; vendor and food booths operate on the other three days.','https://festivalprovo.com/festival-info.php',['Labor Day'],flags=['Outdoor'],communities=['Latino / Hispanic'],notable=True,bydate={'2026-09-04':'5:45–10 PM','2026-09-05':'10 AM–10 PM','2026-09-06':'6–8 PM','2026-09-07':'10 AM–10 PM'})
add('Polynesian Days Utah','2026-09-04','2026-09-07',U,M,'Electric Park, 3003 N Thanksgiving Way, Lehi','See archived performance program','2026 admission: $10 online or $12 at the gate; under 2 free','A cultural festival with Pacific Island music, dance, food, vendors and village experiences. Evening concerts form part of the program.','https://polynesiandaysutah.com/activities',['Labor Day'],notes='Organizer home page lists admission and free east-side parking; performance times vary.',flags=['Outdoor'],communities=['Pacific Islander'],notable=True)
add('Labor Day Luau at Thanksgiving Point','2026-09-07','2026-09-07',U,['Food & Drink','Live Music & Performance','Community & Culture'],'Waterfall Amphitheatre, Ashton Gardens, Lehi','Doors and dinner 6 PM; show 7:30 PM','2026 advance: adult $35; ages 3–12 $27; under 3 $10; VIP $49. Day-of adult $40, child $32, VIP $55','A Hawaiian-inspired dinner followed by Pacific Island dances and storytelling in an outdoor garden amphitheatre. General admission uses designated blanket and chair sections.','https://thanksgivingpoint.org/events/labor-day-luau/',['Labor Day'],notes='2026 tickets sold out. Accessible paths and parking are available; wheelchair seating is at the rear. Mobility devices are not rented.',flags=['Outdoor','Advance booking'],communities=['Pacific Islander'],accessibility={'summary':'Accessible paths and parking; wheelchair seating at rear of amphitheatre.','sourceUrl':'https://thanksgivingpoint.org/events/labor-day-luau/'})
add('Park City Miners Day','2026-09-07','2026-09-07',P,M,'Main Street and City Park, Park City','7:30 AM–4 PM; parade 11 AM','Free parade and park activities; breakfast, race, ball entries and purchases extra','Park City’s mining heritage celebration features the Running of the Balls, a Main Street parade, live music, children’s games and mucking and drilling competitions.','https://parkcityminersday.org/pages/schedule-of-events',['Labor Day'],flags=['Outdoor'],notable=True)
add('Moab Music Festival Labor Day Community Concert','2026-09-07','2026-09-07',E,['Live Music & Performance'],'Old City Park, Old City Park Rd and Murphy Lane, Moab','2 PM','Free admission','An outdoor concert with R. Carlos Nakai, Sam Reider and the Human Hands, and festival chamber musicians. Bring a blanket or camp chair for the shaded lawn; picnics are welcome.','https://moabmusicfest.org/events/rmp-community-concert-2026/',['Labor Day'],notes='Some folding chairs and free parking were provided. Pets are not permitted.',flags=['Outdoor'])
add('History of Camp Floyd Day','2026-09-07','2026-09-07',U,C,'Camp Floyd State Park Museum, 69 W Main St, Fairfield','10 AM–4 PM','$5 per person or $15 per immediate family','Living history demonstrations, cannon and musket firing, museum exhibits and the Stagecoach Inn illustrate camp life in Utah Territory.','https://stateparks.utah.gov/event/history-of-camp-floyd-day-2/',['Labor Day'],notes='Food sold separately.',flags=['Outdoor'])
add('Afro Utah Festival','2026-09-05','2026-09-05',S,M,'Salt Lake City Public Library, 210 E 400 S, Salt Lake City','Starts at noon','Free admission; free RSVP requested','A public celebration of African and diaspora cultures with music, dance, fashion, food and family activities at the city library.','https://afroutah.org/festival',['Labor Day'],flags=['Outdoor','Registration requested'],communities=['Black / African diaspora'],notable=True)
add('Railroaders Festival at Golden Spike','2026-09-05','2026-09-05','Box Elder County',C,'Golden Spike National Historical Park, Promontory Summit','9 AM–5 PM','$20 per vehicle; federal interagency passes accepted','Historic locomotives, motor-car demonstrations, frontier games and ranger programs explore the railroad’s history at Promontory Summit.','https://www.nps.gov/planyourvisit/event-details.htm?id=0A88586A-E5A1-B17A-34C329320B31F707',['Labor Day'],flags=['Outdoor'])
# Regional festivals, arts and heritage.
add('Utah State Fair','2026-09-10','2026-09-20',S,M,'Utah State Fairpark, 155 N 1000 W, Salt Lake City','Hours vary by day; see archived fair FAQ','Paid gate admission; rides, parking and some arena events extra. Archived gate tariff needs confirmation','Livestock exhibits, competitions, fair food, carnival rides, concerts and arena shows fill the Fairpark. Gate admission and individual attractions have separate pricing.','https://www.utahstatefair.com/events/2026/utah-state-fair',notes='Scooter rentals were available inside Gate Y; arena admission may include same-day fair entry.',flags=['Outdoor'],notable=True)
add('Draper International Arts & Crafts Festival','2026-09-12','2026-09-12',S,M,'Draper Park, Draper','10 AM–4 PM','Free admission and parking','Handmade artisan booths share the park with cultural dance and music performances, food vendors, storytelling, puppet shows and free children’s crafts.','https://www.draperutah.gov/events-programs/community-events/international-arts-crafts-festival/',flags=['Outdoor'])
add('9th & 9th Street Festival','2026-09-19','2026-09-19',S,M,'900 East and 900 South, Salt Lake City','10 AM–6 PM','Free admission; food and purchases extra','A neighborhood street festival with local artists, vendors, food and live music at the 9th & 9th intersection.','https://9thand9thstreetfestival.com/',flags=['Outdoor'])
add('Old Capitol Arts & Living History Festival','2026-09-11','2026-09-12',SO,M,'Territorial Statehouse State Park, Fillmore','See archived festival program','Free admission; food and purchases extra','Living history demonstrations, art vendors, music, Native American dance and family activities take place beside Utah’s historic Territorial Statehouse.','https://stateparks.utah.gov/event/old-capitol-arts-and-living-history-festival/',flags=['Outdoor'])
add('Freedom’s Light Festival','2026-09-17','2026-09-19',D,C,'Bountiful City Park, Bountiful','Thu 9 AM–4 PM; Fri 9 AM–9 PM; Sat 9 AM–4 PM','Free admission','Costumed historical presenters and hands-on activities introduce the American Constitution and the people involved in its creation.','https://kaysville.gov/Calendar.aspx?EID=2839',flags=['Outdoor'],bydate={'2026-09-17':'9 AM–4 PM','2026-09-18':'9 AM–9 PM','2026-09-19':'9 AM–4 PM'})
add('Logan Pride Festival','2026-09-19','2026-09-19',L,['Community & Culture','Live Music & Performance'],'Federal Avenue, downtown Logan','Performances start 10 AM','See archived festival admission information','An LGBTQ+ community festival with live musicians, drag performers and community gathering on Federal Avenue.','https://loganpride.org/festival-performers/',['Pride'],flags=['Outdoor'],communities=['LGBTQ+'],notable=True)
add('Pride of Southern Utah: Pride in the Park','2026-09-26','2026-09-26',SU,M,'JC Snow Park, St. George','11 AM–5 PM','Free admission; free ticket required','An all-ages LGBTQ+ festival with local performers, vendors and food trucks, headlined by Lyndy Butler and the Moonflowers. Entry includes bag checks and metal detectors.','https://www.prideofsouthernutah.org/events/posu/pride2024-h8df4-3tbhd',['Pride'],notes='Accessible drop-off is available at the entrance; general parking is in neighboring lots.',flags=['Outdoor','Registration required'],communities=['LGBTQ+'],notable=True,accessibility={'summary':'Entrance drop-off permitted for attendees with disabilities or mobility limitations.','sourceUrl':'https://www.prideofsouthernutah.org/events/posu/pride2024-h8df4-3tbhd'})
add('Fiestas Américas at Utah State University','2026-10-02','2026-10-02',L,['Community & Culture','Live Music & Performance'],'Evan N. Stevenson Ballroom, Taggart Student Center, Logan','6–10 PM','See archived university event information','A Latin American heritage celebration with a photo and flag display, a flag parade, cultural performances and Ballet Folklórico de Efraín Villalobos. Everyone is welcome.','https://huntsman.usu.edu/focusedfridays/calendar/?audience=5&id=104755',['Hispanic Heritage Month'],communities=['Latino / Hispanic'])
add('Utah Symphony: Celebración Sinfónica','2026-09-21','2026-09-21',S,['Live Music & Performance','Community & Culture'],'Abravanel Hall, Salt Lake City','7 PM','Ticketed; archived 2026 ticket prices unverified','The Utah Symphony performs Latin American classical and popular music with conductor Enrico Lopez-Yañez, soprano Mónica Ábrego and Ballet Las Americas de Utah.','https://www.saltlakecountyarts.org/events/celebracion-sinfonica/',['Hispanic Heritage Month'],communities=['Latino / Hispanic'])
add('Red Rock Arts Festival','2026-09-25','2026-09-27',E,['Community & Culture','Workshops & Learning','Markets & Shopping','Live Music & Performance'],'Moab Arts Center, 111 E 100 N, Moab','Workshop and street-festival schedules vary','Free community workshops and street-festival activities; purchases extra','An arts weekend with hands-on workshops, a street festival, live music, artisan vendors and a chalk competition.','https://moabcity.gov/Calendar.aspx?EID=1323',flags=['Outdoor'])
add('Red Rock Film Festival','2026-09-23','2026-09-26',SU,['Community & Culture','Live Music & Performance'],'The PAC, St. George','Screening times vary; see archived Eventive program','Paid passes and individual screenings; archived prices need confirmation','Independent film screenings, premieres, filmmaker conversations and panels make up this Southern Utah film festival.','https://www.redrockfilmfestival.com/index.html',notable=True)
add('PhenomeCon','2026-09-09','2026-09-12',E,['Community & Culture','Workshops & Learning'],'Uintah Conference Center, 313 E 200 S, Vernal','Talks and activities follow the conference agenda','2026: single day $50; two days $100; four days $149; VIP $349; optional activities extra','A paranormal-themed conference with speakers, presentations, vendors, socials and optional field activities. Expect discussion of unexplained phenomena rather than a haunted-house experience.','https://www.phenomecon.net/pricing',notable=True)
add('Timpanogos Storytelling Festival','2026-09-10','2026-09-12',U,['Live Music & Performance','Community & Culture'],'Ashton Gardens, Lehi','Thu 3–9 PM; Fri and Sat programs throughout day and evening','2026 full event: adult $85, senior/student $75, ages 3–12 $50. Adult Fri/Sat day $60; evening tickets $5–$20','Professional storytellers perform personal stories, folktales, humorous tales and evening showcases in garden venues. Day and evening tickets offer different ways to attend.','https://timpfest.org/tickets/',flags=['Outdoor','Advance booking'],notable=True)
add('Garden of Quilts','2026-09-18','2026-09-19',U,['Community & Culture','Workshops & Learning','Markets & Shopping'],'Ashton Gardens, 3900 N Garden Dr, Lehi','Fri 9 AM–4 PM; Sat 9 AM–6 PM','2026 one-day exhibition $35; two days $60; member rates $10/$18; classes extra','Hundreds of quilts displayed outdoors turn Ashton Gardens into a textile-art exhibition, with trunk shows, demonstrations and a separate vendor marketplace.','https://thanksgivingpoint.org/events/garden-of-quilts/',notes='Friday exhibition closed early for severe weather. Meet the Maker was cancelled. Classes ran Sep 16–19 and used separate registration.',flags=['Outdoor'],bydate={'2026-09-18':'9 AM–4 PM','2026-09-19':'9 AM–6 PM'})
add('Woodshed Music Festival','2026-09-18','2026-09-19',I,['Live Music & Performance','Food & Drink'],'Willow Glen Resort, Cedar City','See archived stage schedule','Ticketed; children 12 and under, veterans and first responders with valid ID admitted free at door; paid tariff unverified','Two days of live music across three stages, with Ben Haggard headlining Saturday, plus food, vendors and optional camping.','https://willowglen.ticketspice.com/woodshed-festival',flags=['Outdoor'])
add('Deer Valley Mountain Beer Festival','2026-09-19','2026-09-20',P,['Food & Drink','Live Music & Performance','Active & Outdoors'],'Silver Lake Lodge; check-in at Snow Park Lodge, Deer Valley','Noon–5 PM','2026 ages 21+: admission $45; tasting packages $70/$90/$155. Under-21 non-drinking entry $20','Utah brewery tastings, scenic chairlift access, live music and a children’s zone share the mountain setting. The Friday Brewmaster Dinner is a separate event.','https://www.deervalley.com/things-to-do/activities/mountain-beer-festival',notes='Alcohol service requires age 21+; the festival itself permits non-drinking younger guests. Dogs not permitted.',flags=['Outdoor'])
add('Rocky Mountain ATV Jamboree','2026-09-14','2026-09-18',SO,A,'Richfield City Park staging area and regional trails, Richfield','Guided departures vary by selected ride','$150 per rider for 2026 registration','Five days of guided ATV and UTV rides explore trails around Richfield. Registration includes a shirt and scheduled group meals; riders choose routes suited to their experience.','https://richfieldutah.com/rocky-mountain-jamboree/',notes='Bring the required vehicle and riding equipment. Registration closed Sep 1.',flags=['Outdoor','Registration required'])
add('LoToJa Classic','2026-09-12','2026-09-12',L,A,'Start: 150 N 100 E, Logan; finish in Jackson, Wyoming','Start waves 5:30–6:58 AM','Participant registration required; archived entry tariff needs confirmation','An endurance cycling event begins in Logan and travels to Jackson through Utah, Idaho and Wyoming. This is a demanding registered ride, with race and recreational categories.','https://lotoja.com/eventinfo/EventSchedule',notes='Route crosses state lines; the Utah listing covers its Logan start.',flags=['Outdoor','Registration required'])
add('Nature & Rhythm Drum Circle','2026-09-04','2026-09-04',S,['Community & Culture','Workshops & Learning'],'Pioneer Crossing Regional Park, West Valley City','7–8 PM','Free admission','A guided outdoor drum circle combines percussion and river sounds. Instruments are provided and people of all ages and abilities are welcome.','https://jordanrivercommission.gov/event/nature-rhythm-drum-circle-september-4-2026/',flags=['Outdoor'],recurrence='one-off')
add('Cycle of Life Plein Air Festival','2026-09-26','2026-09-26',S,['Community & Culture','Workshops & Learning'],'Conservation Garden Park, West Jordan','10 AM–4 PM','Free admission','Artists of all ages create outdoors using the garden’s plants, water, pollinators and visitors as subjects. This is participatory art-making rather than an art market.','https://jordanrivercommission.gov/event/cycle-of-life-plein-air-festival-september-26-2026/',flags=['Outdoor'],recurrence='one-off')
add('Bluffdale Get to the River Family Festival & Safety Fair','2026-09-15','2026-09-15',S,C,'Day Ranch Park, Bluffdale','6:30–8 PM','See archived city event information','A family gathering with an art project, food trucks, bike and e-bike safety, car-seat checks and CarFit checks for older adults.','https://bluffdale.gov/river',flags=['Outdoor'])
add('Bird Walk at Fielding Garr Ranch','2026-09-09','2026-09-09',D,A,'Fielding Garr Ranch picnic area, Antelope Island State Park','9–10 AM','No additional activity charge; regular park entry applies','A guided walk through the ranch’s wetland habitat looks for local birds. Binoculars are available to borrow.','https://stateparks.utah.gov/event/bird-walk-at-fielding-garr-ranch-22/',flags=['Outdoor'],recurrence='recurring')
add('Snowbird Oktoberfest','2026-08-08','2026-10-11',S,['Community & Culture','Food & Drink','Live Music & Performance','Markets & Shopping'],'Snowbird Center, Snowbird','Saturdays and Sundays, plus Labor Day; noon–6 PM','Free admission; parking $15 in designated lots, valet $30; food, drinks and activities extra','Bavarian music, food, beer tastings and local vendors fill the Snowbird Center and festival tent. Families can visit together; alcohol purchases require proof of legal drinking age.','https://www.snowbird.com/activities-events/oktoberfest/snowbird-oktoberfest/',['Oktoberfest','Labor Day'],notes='Free shuttles depart from the park-and-ride at 9400 S Highland Dr. Reservations guarantee a ride; walk-up seats depend on availability.',flags=['Outdoor'],notable=True,recurrence='seasonal')
if new and new[-1]['id']=='snowbird-oktoberfest-2026':
 e=new[-1];a=datetime.date(2026,8,8);b=datetime.date(2026,10,11);e['occurrenceDates']=[(a+datetime.timedelta(days=i)).isoformat() for i in range((b-a).days+1) if (a+datetime.timedelta(days=i)).weekday() in [5,6] or (a+datetime.timedelta(days=i)).isoformat()=='2026-09-07'];e['2026 schedule']=', '.join(e['occurrenceDates']);e['sourceRow']=639;e['costCount']=1
# No artificial publication backdating. Discovery date remains the actual verification date.
d['meta']['eventCount']=len(d['events']);d['meta']['confirmedCount']=sum(not e['isWatch'] for e in d['events']);d['meta']['watchCount']=sum(e['isWatch'] for e in d['events'])
p.write_text('window.SITE_DATA = '+json.dumps(d,ensure_ascii=False,indent=2)+';\n');ledger=pathlib.Path('research/september-backfill-2026-10-06.json');previous=json.loads(ledger.read_text()) if ledger.exists() else [];ledger.write_text(json.dumps(list({e['id']:e for e in previous+new}.values()),ensure_ascii=False,indent=2));print('Added',len(new),'source-backed events')
