import json,re,datetime,pathlib
p=pathlib.Path('assets/data.js');d=json.loads(p.read_text().removeprefix('window.SITE_DATA = ').rstrip(';\n'))
def add(name,holiday,date,time,location,source,desc,types,price='Price not announced',**extra):
 slug=re.sub('[^a-z0-9]+','-',name.lower()).strip('-')
 if any(e['id']==slug for e in d['events']):return
 e={'id':slug,'Event / attraction':name,'holidays':holiday,'primaryHoliday':holiday[0],'First date':date,'startDate':date,'endDate':date,'2026 schedule':date or 'Dates to be announced','Times':time,'Location':location,'Website':source,'Why / thoughts':desc,'Extra notes':'','Age':'General audience','Price':price,'Cost':'','costCount':1 if price=='Free' else 0,'isFree':price=='Free','ghostCount':0,'publicRegion':'Salt Lake City','publicTypes':types,'categories':types,'sourceCategories':types,'Region':'Salt Lake City','Status':'Confirmed organizer listing','isWatch':False,'socials':[],'photo':None,'flags':[],'rating':None,'artKey':'community','occurrenceDates':[date] if date else [],'scheduleConfidence':'verified-dates' if date else 'unresolved','timezone':'America/Denver','lastVerified':'2026-10-06','travelTier':'Core / easy day trip',**extra};d['events'].append(e)
add('EVE Rooftop Afterlive',['Halloween & Fall'],'2026-10-31','Doors 8:00 PM; closing time not announced','EVE SLC, 609 S State St, Salt Lake City','https://eveinslc.com/single-event/EVE164431400120261031/eve-rooftop-afterlive/','Spend Halloween on EVE’s rooftop. The venue lists doors at 8 PM; confirm admission and entry requirements before booking.',['Nightlife & Parties'],flags=['Rooftop','Nightlife'])
add('EVE Halloween Crawl',['Halloween & Fall'],'2026-10-29','Doors 8:00 PM; closing time not announced','EVE SLC, 609 S State St, Salt Lake City','https://eveinslc.com/single-event/EVE164431400020261029/halloween-crawl/','A Halloween crawl listed on EVE’s October calendar. Check the event page for tickets and the route.',['Nightlife & Parties'])
add('Salt Lake Men’s Choir: Somewhere In My Memory',['Christmas'],'2026-12-11','Performance time to be announced','777 S 1300 E, Salt Lake City','https://events.com/r/en_US/tickets/salt-lake-mens-choir-presents-somewhere-in-my-memory-salt-lake-city-december-1071191','Holiday songs and memories with the Salt Lake Men’s Choir and guest artist Sofrona Snow. General admission seating; advance booking is recommended.',['Live Music & Performance'],flags=['LGBTQ+ community','Advance booking recommended'],scheduleNote='The linked ticket page identifies December 11; additional performances and showtimes are awaiting confirmation.')
add('Winter Craftacular',['Winter'],'2026-12-05','10:30 AM–12:00 PM','Salt Lake County Library — check the event page for the branch','https://slcls.libnet.info/event/16763517','Make up to three crafts to take home at this winter craft morning.',['Workshops & Learning'],publicRegion='Salt Lake Valley',scheduleNote='Check the event page for the branch and any registration requirements.')
for e in d['events']:
 if e['id']=='winter-celebrations':e['Website']='https://slcls.libnet.info/event/17068851';e['Times']='11:00 AM–1:00 PM';e['Why / thoughts']='Explore several winter faith traditions through crafts at Whitmore Library.'
 if e['id']=='paag-thanksgiving-dinner':e['2026 schedule']='Date awaiting organizer clarification';e['scheduleNote']='The page lists November 20 in its header and November 21 in its description. Confirm the date with PAAG.';e['occurrenceDates']=[];e['isWatch']=True;e['isFree']=False;e['Price']='Admission details to be confirmed'
 if e['id']=='diwali-family-celebration':e['isWatch']=True;e['Status']='Awaiting primary organizer confirmation';e['occurrenceDates']=[]
 if e['id']=='hallows-eve-monster-bash':e['Times']='8:30 PM–midnight';e['Price']='Standard $75; pair $130; VIP table for six $1,110, plus taxes and fees';e['flags']=['21+','Photo ID','Costumes required','Fog / haze / lasers'];e['Extra notes']='Doors open at 8 PM; VIP early entry at 7:30 PM. Theatrical fog, haze and lasers are part of the show. No weapons or replica weapons.'
 if e['id']=='celebrate-in-saratoga-silent-santa':e['Extra notes']='Registration opens November 1. Saratoga Springs residents have priority through November 15, then remaining appointments open to everyone. Book one 10-minute appointment per family; no age limit.';e['accessibility']={'summary':'Adaptive Santa visits by appointment; no age limit','url':e['Website'],'tone':'positive'};e['flags']+=['Adaptive appointments','Resident priority','Reservation required']
 if e.get('isWatch'):e['occurrenceDates']=[]
 # Add cultural affiliation only when explicit in the event record, independent from holiday tags.
 text=' '.join([e['Event / attraction'],e.get('Category',''),e.get('Age',''),e.get('Why / thoughts','')])
 e['communities']=[x for x,rx in [('LGBTQ+','queer|lgbtq|drag|salt lake men'),('Christian','nativity|messiah|tabernacle choir|christian'),('Jewish','hanukkah|chanukah|menorah'),('South Asian','diwali|hindu'),('Pagan / alternative','pagan|yule|krampus')] if re.search(rx,text,re.I)]
 if e.get('rating') and any(h in e['holidays'] for h in ['Hanukkah','Diwali','Kwanzaa','Veterans Day']):e['rating']=None
 e['flags']=list(dict.fromkeys(e['flags']))[:12]
d['meta'].update(eventCount=len(d['events']),confirmedCount=sum(not e['isWatch'] for e in d['events']),watchCount=sum(e['isWatch'] for e in d['events']))
p.write_text('window.SITE_DATA = '+json.dumps(d,ensure_ascii=False,separators=(',',':'))+';\n')
print(d['meta']['eventCount'],'events',d['meta']['confirmedCount'],'confirmed')
